# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_feedback_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
