# Generated by Django 5.0.6 on 2024-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_withdrawalnotice_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalnotice',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
