# Generated by Django 5.0.6 on 2024-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_withdrawalnotice_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalnotice',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
