# Generated by Django 5.0.6 on 2024-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_withdrawalnotice_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalnotice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
