# Generated by Django 5.0.6 on 2024-06-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_alter_withdrawalnotice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithdrawalNotice',
            new_name='checkout',
        ),
    ]
