# Generated by Django 5.0.6 on 2024-06-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
